name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CACHE_NAME: darksoil-studio
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: cachix/cachix-action@v14
        with:
          name: "${{ env.CACHE_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build 
        run: nix build -L
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        run: |
          cachix push $CACHE_NAME ./result
          # --agent is needed due to a regression in Cachix 1.1, which will be fixed in Cachix 1.2
          cachix deploy activate --agent file-storage-provider-aon ./result

